version: '2.5'
services:
 fyle-assignment:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:7755"
    environment:
      - FLASK_APP=core/server.py
      - DATABASE_URL=sqlite:///./store.sqlite3